--- 
networks: 
  vpcbr: 
    driver: bridge
    ipam: 
      config: 
        - 
          gateway: "10.1.1.1"
          subnet: 10.1.1.0/24
services: 
  ky_db: 
    container_name: db
    environment: 
      MYSQL_DATABASE: CT519_Movie
      MYSQL_PASSWORD: p@ssword
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_USER: KSY
    image: "mysql:5.6"
    networks: 
      vpcbr: 
        ipv4_address: "10.1.1.22"
    ports: 
      - "3306:3306"
    restart: always
    volumes: 
      - "./mysql-backup/:/docker-entrypoint-initdb.d/"
  ky_web: 
    build: 
      context: ./
      dockerfile: dockerfile-php
    container_name: ky_web
    depends_on: 
      - ky_db
    networks: 
      vpcbr: 
        ipv4_address: "10.1.1.11"
    ports: 
      - "80:80"
    restart: always
    volumes: 
      - "./www/:/var/www/html/"
version: "3.9"

